### ISSUE TITLE
some questions about evaluate

### ISSUE THREAD

**Issue by sakura073** [Sohanpatnaik106/CABINET_QA#3]
Traceback (most recent call last):
  File "/root/CABINET_QA/evaluate.py", line 39, in <module>
    dataset = load_dataset("/root/CABINET_QA/datasets/WikiTableQuestions", recursive=True)
  File "/root/miniconda3/envs/tabllm/lib/python3.9/site-packages/datasets/load.py", line 2109, in load_dataset
    builder_instance = load_dataset_builder(
  File "/root/miniconda3/envs/tabllm/lib/python3.9/site-packages/datasets/load.py", line 1795, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/root/miniconda3/envs/tabllm/lib/python3.9/site-packages/datasets/load.py", line 1424, in dataset_module_factory
    return LocalDatasetModuleFactoryWithoutScript(
  File "/root/miniconda3/envs/tabllm/lib/python3.9/site-packages/datasets/load.py", line 853, in get_module
    patterns = sanitize_patterns(self.data_files) if self.data_files is not None else get_data_patterns(base_path)
  File "/root/miniconda3/envs/tabllm/lib/python3.9/site-packages/datasets/data_files.py", line 457, in get_data_patterns
    return _get_data_files_patterns(resolver)
  File "/root/miniconda3/envs/tabllm/lib/python3.9/site-packages/datasets/data_files.py", line 248, in _get_data_files_patterns
    data_files = pattern_resolver(pattern)
  File "/root/miniconda3/envs/tabllm/lib/python3.9/site-packages/datasets/data_files.py", line 332, in resolve_pattern
    fs, _, _ = get_fs_token_paths(pattern, storage_options=storage_options)
  File "/root/miniconda3/envs/tabllm/lib/python3.9/site-packages/fsspec/core.py", line 684, in get_fs_token_paths
    paths = [f for f in sorted(fs.glob(paths)) if not fs.isdir(f)]
  File "/root/miniconda3/envs/tabllm/lib/python3.9/site-packages/fsspec/spec.py", line 611, in glob
    pattern = glob_translate(path + ("/" if ends_with_sep else ""))
  File "/root/miniconda3/envs/tabllm/lib/python3.9/site-packages/fsspec/utils.py", line 729, in glob_translate
    raise ValueError(
ValueError: Invalid pattern: '**' can only be an entire path component
how can I solve this problem

**Comment by euler-666** [comment]
Please load the dataset with the correct huggingface path. For WikiTQ dataset, use the following line
`dataset = load_dataset("Stanford/wikitablequestions", trust_remote_code=True)`

Also, verify if the environment was created with the specified yml file.

**Comment by sakura073** [comment]
> Please load the dataset with the correct huggingface path. For WikiTQ dataset, use the following line `dataset = load_dataset("Stanford/wikitablequestions", trust_remote_code=True)`
> 
> Also, verify if the environment was created with the specified yml file.

have new problem
(my-env) root@autodl-container-a4884eab4c-2f5b2e8c:~/CABINET# python evaluate.py
2024-11-14 14:05:09.767656: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-11-14 14:05:09.770639: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-11-14 14:05:09.823507: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI AVX512_BF16 AVX_VNNI AMX_TILE AMX_INT8 AMX_BF16 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-11-14 14:05:10.840916: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2024-11-14 14:05:11.680714: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1960] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
Downloading builder script: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8.56k/8.56k [00:00<00:00, 31.1MB/s]
Downloading readme: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7.63k/7.63k [00:00<00:00, 27.4MB/s]
Downloading data: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 29.3M/29.3M [00:00<00:00, 81.2MB/s]
Generating train split: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 11321/11321 [00:03<00:00, 2860.38 examples/s]
Generating test split: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4344/4344 [00:01<00:00, 2610.17 examples/s]
Generating validation split: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 2831/2831 [00:00<00:00, 3432.13 examples/s]
Traceback (most recent call last):
  File "/root/CABINET/evaluate.py", line 37, in <module>
    dataset = load_dataset("Stanford/wikitablequestions")
  File "/root/miniconda3/envs/my-env/lib/python3.10/site-packages/datasets/load.py", line 2146, in load_dataset
    ds = builder_instance.as_dataset(split=split, verification_mode=verification_mode, in_memory=keep_in_memory)
  File "/root/miniconda3/envs/my-env/lib/python3.10/site-packages/datasets/builder.py", line 1173, in as_dataset
    raise NotImplementedError(f"Loading a dataset cached in a {type(self._fs).__name__} is not supported.")
NotImplementedError: Loading a dataset cached in a LocalFileSystem is not supported.
